cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path(
        'add/<int:product_id>/',
        views.cart_add,
        name='cart_add'
    ),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove'
    )
]

coupons/urls.py
from django.urls import path

from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

onlineshop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('products/', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('shop/', views.ProductList.as_view(), name='product_list'),
    path('<slug:category_slug>/', views.ProductList.as_view(), name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.ProductDetails.as_view(), name='product_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [ (i, str(i)) for i in range(1, 21) ]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )

    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from . cart import Cart
from . forms import CartAddProductForm
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            update_quantity=cd['update']
        )

    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)

    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'update': True
            }
        )

    return render(request, 'cart/detail.html', {
        'cart': cart,
        'coupon_apply_form': CouponApplyForm(),
    })

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
    <!-- shopping-cart-area start -->
    <div class="cart-main-area ptb-100">
        <div class="container">
            <h3 class="page-title">Your cart items</h3>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="table-content table-responsive">
                        <table>
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product Name</th>
                                    <th>Unit Price</th>
                                    <th>Qty</th>
                                    <th>Subtotal</th>
                                    <th>Options</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cart %}
                                
                                    {% with product=item.product %}
                                        <tr>
                                            <td class="product-thumbnail">
                                                <a href="{{ product.get_absolute_url }}">
                                                    <img src="{% if product.image %}{{ product.image.url }} {% else %}{% static 'images/no_image.jpg' %}{% endif %}" width="80">
                                                </a>
                                            </td>
                                            <td class="product-name"><a href="{{ product.get_absolute_url }}">{{product.name|title}}</a></td>
                                            <td class="product-price-cart"><span class="amount">${{product.price}}</span></td>
                                            <td class="product-quantity">
                                                <div class="pro-dec-cart">
                                                    <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                                        
                                                        {{ item.update_quantity_form.quantity }}                                                    
                                                        {{ item.update_quantity_form.update }}
                                                        {% csrf_token %}

                                                        <button type="submit"><span>Update</span></button>
                                                    </form>
                                                </div>
                                            </td>
                                            <td class="product-subtotal">${{ item.total_price }}</td>
                                            <td class="product-remove">
                                                <a href="{% url 'cart:cart_remove' product.id%}"><i class="fa fa-times"></i></a>
                                            </td>
                                        </tr>
                                    {% endwith %}

                                {% endfor %}
                                
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="cart-shiping-update-wrapper">
                                <div class="cart-shiping-update">
                                    <a href="{% url 'shop:product_list' %}">Continue Shopping</a>
                                </div>
                                <div class="cart-clear">
                                    <a href="#">Clear Shopping Cart</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4 col-md-6">
                            <div class="discount-code-wrapper">
                                <div class="title-wrap">
                                    <h4 class="cart-bottom-title section-bg-gray">Use Coupon Code</h4> 
                                </div>
                                <div class="discount-code">
                                    <p>Enter your coupon code if you have one.</p>
                                    <form action="{% url "coupons:apply" %}" method="post">
                                        {% csrf_token %}
                                        {{ coupon_apply_form.code }}
                                        <button class="cart-btn-2" type="submit">Apply Coupon</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-8 col-md-12">
                            <div class="grand-totall">
                                <div class="title-wrap">
                                    <h4 class="cart-bottom-title section-bg-gary-cart">Cart Total</h4>
                                </div>
                                <h5>Total products <span>${{ cart.get_total_price|floatformat:"2" }}</span></h5>
                                
                                {% if cart.coupon %}
                                    <div class="total-shipping">
                                        <ul>
                                            <li><span>{{ cart.coupon.code }}</span></li>
                                            <li><span>{{ cart.coupon.discount }}% off</span></li>
                                            <li><span>${{ cart.get_discount|floatformat:"2" }}</span></li>                                            
                                        </ul>                                        
                                    </div>
                                {% endif %}

                                <h4 class="grand-totall-title">Grand Total  <span>${{ cart.get_total_price_after_discount|floatformat:"2" }}</span></h4>
                                <a href="{% url 'orders:order_create' %}">Proceed to Checkout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}