cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path(
        'add/<int:product_id>/',
        views.cart_add,
        name='cart_add'
    ),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove'
    )
]

onlineshop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('products/', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('shop/', views.ProductList.as_view(), name='product_list'),
    path('<slug:category_slug>/', views.ProductList.as_view(), name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.ProductDetails.as_view(), name='product_detail'),
]

pages/templates/pages/about.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}About{% endblock title %}

{% block content %}

    <!-- Breadcrumb Area Start -->
    <div class="breadcrumb-area bg-image-3 ptb-150" style="background-image: url({% static 'images/breadcrumb.jpg' %})">
        <div class="container">
            <div class="breadcrumb-content text-center">
                <h3>ABOUT US</h3>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Area End -->


    <!-- About Us Area Start -->
    <div class="about-us-area pt-100 pb-100">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-12 d-flex align-items-center">
                    <div class="overview-content-2">
                        <h4>Welcome To</h4>
                        <h2>Our TeaCorp Store!</h2>
                        <p class="peragraph-blog">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                        </p>
                        <p>
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                        </p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12">
                    <div class="overview-img text-center">
                        <a href="#">
                            <img src="{% static 'images/about-us.jpg' %}" alt="About us image">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About Us Area End -->


    <!-- Team Area Start -->
    <div class="team-area pt-95 pb-70">
        <div class="container">
            <div class="product-top-bar section-border mb-50">
                <div class="section-title-wrap style-two text-center">
                    <h3 class="section-title">Team Members</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="team-wrapper mb-30">
                        <div class="team-img">
                            <a href="#">
                                <img src="{% static 'images/team-1.jpg' %}" alt="">
                            </a>
                            <div class="team-action">
                                <a class="action-plus facebook" href="#">
                                    <i class="ion-social-facebook"></i>
                                </a>
                                <a class="action-heart twitter" title="Wishlist" href="#">
                                    <i class="ion-social-twitter"></i>
                                </a>
                                <a class="action-cart instagram" href="#">
                                    <i class="ion-social-instagram"></i>
                                </a>
                            </div>
                        </div>
                        <div class="team-content text-center">
                            <h4>Bob Lee</h4>
                            <span>Manager </span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="team-wrapper mb-30">
                        <div class="product-img">
                            <a href="product-details.html">
                                <img src="{% static 'images/team-2.jpg' %}" alt="">
                            </a>
                            <div class="team-action">
                                <a class="action-plus facebook" href="#">
                                    <i class="ion-social-facebook"></i>
                                </a>
                                <a class="action-heart twitter" title="Wishlist" href="#">
                                    <i class="ion-social-twitter"></i>
                                </a>
                                <a class="action-cart instagram" href="#">
                                    <i class="ion-social-instagram"></i>
                                </a>
                            </div>
                        </div>
                        <div class="team-content text-center">
                            <h4>Julie</h4>
                            <span>Developer </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Team Area End -->

{% endblock content %}

pages/templates/pages/contact.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}Contact Us{% endblock title %}

{% block content %}

    <!-- Breadcrumb Area Start -->
    <div class="breadcrumb-area bg-image-3 ptb-150" style="background-image: url({% static 'images/breadcrumb.jpg' %})">
        <div class="container">
            <div class="breadcrumb-content text-center">
                <h3>CONTACT US</h3>
            </div>
        </div>
    </div>
    <!-- Breadcrumb Area End -->

	<div class="container mt-3">
		<div class="row">
			<div class="col-md-12">
				{% if messages %}
				<ul>
					{% for message in messages %}
						{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
							<li class="alert alert-success">{{message}}</li>						
						{% endif %}
					{% endfor %}
				</ul>
				{% endif %}	
			</div>
		</div>
	</div>

    <!-- Contact Area Start -->
	<div class="contact-us ptb-95">
		<div class="container">
			<div class="row">
				<!-- Contact Form Area Start -->
				<div class="col-lg-6">
					<div class="small-title mb-30">
						<h2>Contact Form</h2>
						<p>There are many variations of passages of Lorem Ipsum available, but the majority Lorem Ipsum available.</p>
					</div>
					<form id="" action="." method="post">
						{% csrf_token %}
						<div class="row">
							<div class="col-lg-6">
								<div class="contact-form-style mb-20">
									{{form.fullname}}
								</div>
							</div>
							<div class="col-lg-6">
								<div class="contact-form-style mb-20">
									{{form.email}}
								</div>
							</div>
							<div class="col-lg-12">
								<div class="contact-form-style mb-20">
									{{form.subject}}
								</div>
							</div>
							<div class="col-lg-12">
								<div class="contact-form-style">
									{{form.message}}
									<button class="submit" type="submit" id="contact_us_btn">SEND MESSAGE</button>
								</div>
							</div>
						</div>
					</form>
					<p class="form-messege"></p>
				</div>
				<!-- Contact Form Area End -->

				<!-- Contact Address Strat -->
				<div class="col-lg-6">
					<div class="small-title mb-30">
						<h2>Contact Address</h2>
						<p>There are many variations of passages of Lorem Ipsum available, but the majority Lorem Ipsum available.</p>
					</div>
					<div class="row">
						<div class="col-lg-12 col-md-12">
							<div class="contact-information mb-30">
								<h4>Our Address</h4>
								<p>House. 9, Road. 12, Widgets. Orled. Sydney. Milaro.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12">
							<div class="contact-information contact-mrg mb-30">
								<h4>Phone Number</h4>
								<p>
									<a href="tel:01234567890">01234 567 890</a>
									<a href="tel:01234567891">01234 567 891</a>
								</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12">
							<div class="contact-information contact-mrg mb-30">
								<h4>Web Address</h4>
								<p>
									<a href="mailto:info@example.com">info@example.com</a>
									<a href="#">www.example.com</a>
								</p>
							</div>
						</div>
					</div>
				</div>
				<!-- Contact Address Strat -->

			</div>
		</div>
	</div>
	<!-- Contact Area Start -->

{% endblock content %}

pages/templates/pages/home.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
Home
{% endblock title %}

{% block content %}

    <!-- Hero Image -->
    <div class="slider-area">
        <div class="slider-active owl-dot-style owl-carousel">
            <div class="single-slider ptb-240 bg-img" style="background-image:url({% static 'images/slider/slider-1.jpg' %});">
                <div class="container">
                    <div class="slider-content slider-animated-1">
                        <h1 class="animated">Want to stay <span class="theme-color">healthy</span></h1>
                        <h1 class="animated">drink chai.</h1>
                        <p>The tea leaf is a product of the Earth's fertile soil, radiant sun and nurturing rain. </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Hero Image End -->

    <!-- featured products -->
    {% static 'images/bg-1.jpg' as featured_products_bg %}
    <div class="product-area bg-image-1 pt-100 pb-95" style="background-image: url({{featured_products_bg}}) ">
        <div class="container">
            <div class="featured-product-active hot-flower owl-carousel product-nav">

                {% for product in object_list %}
                    <div class="product-wrapper">
                        <div class="product-img">
                            <a href="product-details.html">
                                <img alt="" src="{% if product.image %}{{product.image.url}}{% else %} {% static 'images/no_image.jpg' %} {% endif %} ">
                            </a>
                            <span>-20%</span>
                            <div class="product-action">
                                <a class="action-wishlist" href="#" title="Wishlist">
                                    <i class="ion-android-favorite-outline"></i>
                                </a>
                                <a class="action-cart" href="#" title="Add To Cart">
                                    <i class="ion-ios-shuffle-strong"></i>
                                </a>
                                <a class="action-compare" href="#" data-target="#exampleModal" data-toggle="modal" title="Quick View">
                                    <i class="ion-ios-search-strong"></i>
                                </a>
                            </div>
                        </div>
                        <div class="product-content text-left">
                            <div class="product-hover-style">
                                <div class="product-title">
                                    <h4>
                                        <a href="#">{{product.name}}</a>
                                    </h4>
                                </div>
                                <div class="cart-hover">
                                    <h4>
                                        <a href="#">+ {{product.name}}</a>
                                    </h4>
                                </div>
                            </div>
                            <div class="product-price-wrapper">
                                <span>{{product.price}} -</span>
                                <span class="product-price-old">{{product.price}} </span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- end featured products -->


    <!-- Banner to show two chai of the day -->
    <div class="banner-area pt-100 pb-70">
        <div class="container">
            <div class="banner-wrap">
                <div class="row">
                {% for product in products %}
                    <div class="col-lg-6 col-md-6">
                        <div class="single-banner img-zoom mb-30">
                            <a href="{% url 'shop:product_detail' product.id product.slug %}">
                                <img src="{% if product.image %}{{product.image.url}}{% else %} {% static 'images/no_image.jpg' %} {% endif %} " alt="">
                            </a>
                            <div class="banner-content">
                                <h4>-50% Sale</h4>
                                <h5>{{ product.name }}</h5>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <!-- end Banner to show two chai of the day -->

{% endblock content %}