cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path(
        'add/<int:product_id>/',
        views.cart_add,
        name='cart_add'
    ),
    path(
        'remove/<int:product_id>/',
        views.cart_remove,
        name='cart_remove'
    )
]

onlineshop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('products/', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name =  'pages'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact-us/', views.ContactUsView.as_view(), name='contact'),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('shop/', views.ProductList.as_view(), name='product_list'),
    path('<slug:category_slug>/', views.ProductList.as_view(), name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.ProductDetails.as_view(), name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(
        max_length=200,
        db_index=True
    )

    slug = models.SlugField(
        max_length=200,
        unique=True
    )

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            'shop:product_list_by_category',
            args=[self.slug]
        )


class Product(models.Model):
    
    category = models.ForeignKey(
        Category,
        related_name='products',
        on_delete=models.CASCADE
    )

    name = models.CharField(
        max_length=200,
        db_index=True
    )

    slug = models.SlugField(
        max_length=200,
        unique=True
    )

    image = models.ImageField(
        upload_to='products/%Y/%m/%d',
        blank=True
    )

    description = models.TextField(blank=True)

    price = models.DecimalField(max_digits=10, decimal_places=2)

    available = models.BooleanField(default=True)

    created = models.DateTimeField(auto_now_add=True)

    updated = models.DateTimeField(auto_now=True)

    
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse(
            'shop:product_detail',
            args=[self.id, self.slug]
        )

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from . models import Category, Product
from cart.forms import CartAddProductForm



class ProductList(ListView):
    model = Product
    template_name = 'shop/product/list.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        categories = Category.objects.all()
        category_slug = self.kwargs.get('category_slug', None)

        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)    
            context['products'] = context['products'].filter(category=category)
            context['categories'] = categories
            context['category'] = category
        
        return context



class ProductDetails(DetailView):
    template_name = 'shop/product/detail.html'
    model = Product
    context_object_name = 'product'

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}{% endblock %}- Tea Shop</title>

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/slick.css' %}">
        <link rel="stylesheet" href="{% static 'css/chosen.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
        <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
        <link rel="stylesheet" href="{% static 'css/meanmenu.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">

        <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
    </head>
    <body>

        <header class="header-area gray-bg clearfix">
            <div class="header-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-3 col-md-4 col-6">
                            <div class="logo">
                                <a href="/">
                                    <img alt="Logo" src="{% static 'images/logo.png' %}">
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-9 col-md-8 col-6">
                            <div class="header-bottom-right">
                                <div class="main-menu">
                                    <nav>
                                        <ul>
                                            <li class="top-hover">
                                                <a href="/">home</a>
                                            </li>
                                            <li>
                                                <a href="{% url 'shop:product_list' %}">shop</a>
                                            </li>
                                            <li>
                                                <a href="{% url 'pages:about' %}">about</a>
                                            </li>
                                                                                       
                                            <li>
                                                <a href="{% url 'pages:contact' %}">contact</a>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
						
                                <div class="header-cart ml-2 mt-1">
                                    <a href="{% url 'cart:cart_detail' %}">
                                        <div class="cart-icon">
                                            <i class="ti-shopping-cart"></i>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="mobile-menu-area">
                        <div class="mobile-menu">
                            <nav id="mobile-menu-active">
                                <ul class="menu-overflow">
                                    
                                    <li>
                                        <a href="/">HOME</a>                                        
                                    </li>
                                    {% for c in categories %}
                                        <li>
                                            <a href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                        </li>    
                                    {% endfor %}
                                    <li>
                                        <a href="#"> Contact us </a>
                                    </li>

                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </header>
		<!-- header end -->


        <div id="content">
            {% block content %}
            {% endblock %}
        </div>

        <!-- Footer style Start -->
    <footer class="footer-area pt-75 gray-bg-3">
        <div class="footer-top gray-bg-3 pb-35">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="footer-widget mb-40">
                            <div class="footer-title mb-25">
                                <h4>My Account</h4>
                            </div>
                            <div class="footer-content">
                                <ul>
                                    <li><a href="my-account.html">My Account</a></li>
                                    <li><a href="about-us.html">Order History</a></li>
                                    <li><a href="wishlist.html">WishList</a></li>
                                    <li><a href="#">Newsletter</a></li>
                                    <li><a href="about-us.html">Order History</a></li>
                                    <li><a href="#">International Orders</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="footer-widget mb-40">
                            <div class="footer-title mb-25">
                                <h4>Information</h4>
                            </div>
                            <div class="footer-content">
                                <ul>
                                    <li><a href="about-us.html">About Us</a></li>
                                    <li><a href="#">Delivery Information</a></li>
                                    <li><a href="#">Privacy Policy</a></li>
                                    <li><a href="#">Terms & Conditions</a></li>
                                    <li><a href="#">Customer Service</a></li>
                                    <li><a href="#">Return Policy</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="footer-widget mb-40">
                            <div class="footer-title mb-25">
                                <h4>Quick Links</h4>
                            </div>
                            <div class="footer-content">
                                <ul>
                                    <li><a href="#">Support Center</a></li>
                                    <li><a href="#">Term & Conditions</a></li>
                                    <li><a href="#">Shipping</a></li>
                                    <li><a href="#">Privacy Policy</a></li>
                                    <li><a href="#">Help</a></li>
                                    <li><a href="#">FAQS</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="footer-widget footer-widget-red footer-black-color mb-40">
                            <div class="footer-title mb-25">
                                <h4>Contact Us</h4>
                            </div>
                            <div class="footer-about">
                                <p>1234 Station Road, Takanini, Auckland, NZ</p>
                                <div class="footer-contact mt-20">
                                    <ul>
                                        <li>(+008) 254 254 254 25487</li>
                                        <li>(+009) 358 587 657 6985</li>
                                    </ul>
                                </div>
                                <div class="footer-contact mt-20">
                                    <ul>
                                        <li>yourmail@example.com</li>
                                        <li>example@admin.com</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom pb-25 pt-25 gray-bg-2">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="copyright">
                            <p>Copyright © <a href="/">TeaCorp</a>. All Right Reserved.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer style End -->


        <script src="{% static 'js/vendor/jquery-1.12.0.min.js' %}"></script>
        <script src="{% static 'js/vendor/popper.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/vendor/owl.carousel.min.js' %}"></script>

        <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'js/ajax-mail.js' %}"></script>
        <script src="{% static 'js/plugins.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>

    </body>
</html> 